stages:
  - test
  - build

image: golang:1.15

variables:
  GIT_DEPTH: 10

.prepare:
  before_script:
    - go mod download

test:
  extends: .prepare
  stage: test
  needs: []
  script:
    - go test -race ./...
  only:
    refs:
      - merge_requests
      - master

build:
  extends: .prepare
  stage: build
  needs: []
  script:
    - go build -v
  artifacts:
    name: "go-flatpak-demo-${CI_PIPELINE_IID}"
    paths:
      - $CI_PROJECT_DIR/go-flatpak-demo
  only:
    refs:
      - merge_requests
      - master
